site_name: Mkdocs de java
site_description: Aprende cosas sobre java
site_author: Aaron Selles

theme:
  name: material

nav:
  - Inicio: index.md
  - Datos:
    - Tipos de datos: tipos_de_datos.md
    - Variables: variables.md
    - Operadores: operadores.md
  - Lógica: logica.md
  - Programación orientada a objetos:
    - Clases: clases.md
    - Objetos: objetos.md
    - Métodos: metodos.md
    - Constructores: constructores.md
    - Interfaces: interfaces.md
    - Herencia: herencia.md
    - Polimorfismo: poliformismo.md